version: "3.8"
services:
  mongo:
    image: mongo:7
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  api:
    build: .
    restart: unless-stopped
    environment:
      - PORT=3000
      - MONGODB_URI=mongodb://mongo:27017/health_risk_profiler
      - CORS_ORIGIN=http://localhost:5173,http://localhost:3000
    ports:
      - "3000:3000"
    depends_on:
      - mongo

volumes:
  mongo_data:
